# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

# Updates PATH for the Google Cloud SDK.
if [ -f /home/${USER}/google-cloud-sdk/path.bash.inc ]; then
  source "/home/${USER}/google-cloud-sdk/path.bash.inc"
fi

# Updates PATH for MS Azure
PATH=${PATH}:/home/ifont/azure-cli/bin

# Update PATH for Go
PATH=/usr/local/go/bin:/home/ifont/go/bin:${PATH}

# Adds home bin to PATH and export
export PATH=${HOME}/bin:${PATH}
