# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

# Path to the bash it configuration
export BASH_IT="/home/${USER}/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='font'

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# Your place for hosting Git repos. I use this for private repos.
#export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
#export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
#export SCM_CHECK=true

# Set Xterm/screen/Tmux title with only a short hostname.
# Unomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Unset system PROMPT_COMMAND
unset PROMPT_COMMAND

# Custom version controlled scripts
export BASH_IT_CUSTOM="/home/${USER}/.dotfiles/bash-it"

# Load Bash It
source $BASH_IT/bash_it.sh

# Private Functions
if [ -f /home/${USER}/.bash_priv_rc ]; then
    source "/home/${USER}/.bash_priv_rc"
fi

# Enables shell command completion for gcloud.
if [ -f /home/${USER}/google-cloud-sdk/completion.bash.inc ]; then
  source "/home/${USER}/google-cloud-sdk/completion.bash.inc"
fi

# Enables AWS command completion
if [ -f /usr/bin/aws_completer ]; then
  complete -C "/usr/bin/aws_completer" aws
fi

# Enables Azure command completion
source '/home/ifont/azure-cli/az.completion'
