# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

unset rc

# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

# Path to the bash it configuration
export BASH_IT="/home/${USER}/.bash_it"

# Lock and Load a custom theme file
# Leave empty to disable theming.
# location /.bash_it/themes/
export BASH_IT_THEME='font'

# Some themes can show whether `sudo` has a current token or not.
# Set `$THEME_CHECK_SUDO` to `true` to check every prompt:
#THEME_CHECK_SUDO='true'

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# (Advanced): Change this to the name of the main development branch if
# you renamed it or if it was changed for some reason
# export BASH_IT_DEVELOPMENT_BRANCH='master'

# Your place for hosting Git repos. I use this for private repos.
#export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
#export TODO="t"

# Set this to the location of your work or project folders
#BASH_IT_PROJECT_PATHS="${HOME}/Projects:/Volumes/work/src"

# Set this to false to turn off version control status checking within the prompt for all themes
#export SCM_CHECK=false
# Set to actual location of gitstatus directory if installed
#export SCM_GIT_GITSTATUS_DIR="$HOME/gitstatus"
# per default gitstatus uses 2 times as many threads as CPU cores, you can change this here if you must
#export GITSTATUS_NUM_THREADS=8

# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)

# Set Xterm/screen/Tmux title with only a short username.
# Uncomment this (or set SHORT_USER to something else),
# Will otherwise fall back on $USER.
#export SHORT_USER=${USER:0:8}

# If your theme use command duration, uncomment this to
# enable display of last command duration.
#export BASH_IT_COMMAND_DURATION=true
# You can choose the minimum time in seconds before
# command duration is displayed.
#export COMMAND_DURATION_MIN_SECONDS=1

# Set Xterm/screen/Tmux title with shortened command and directory.
# Uncomment this to set.
#export SHORT_TERM_LINE=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Uncomment this to make Bash-it create alias reload.
# export BASH_IT_RELOAD_LEGACY=1

# Custom version controlled scripts
export BASH_IT_CUSTOM="/home/${USER}/.dotfiles/bash-it"

# Load Bash It
source "$BASH_IT"/bash_it.sh

# Private Functions
if [ -f /home/${USER}/.bash_priv_rc ]; then
    source "/home/${USER}/.bash_priv_rc"
fi

# Go Environment
if [ -d $HOME/go/bin ]; then
  if ! [[ "$PATH" =~ "$HOME/go/bin:" ]]; then
    export PATH="$HOME/go/bin:$PATH"
  fi
fi
if [ -f /home/${USER}/.gimme/envs/latest.env ]; then
    source "/home/${USER}/.gimme/envs/latest.env"
fi

# Rust Environment
# Adds cargo bin to PATH
if [ -f "${HOME}/.cargo/env" ]; then
  . "$HOME/.cargo/env"
fi

# Google Cloud SDK
# The next line updates PATH for the Google Cloud SDK.
if [ -f "/home/${USER}/google-cloud-sdk/path.bash.inc" ]; then
  . "/home/${USER}/google-cloud-sdk/path.bash.inc"
fi

# The next line enables shell command completion for gcloud.
if [ -f "/home/${USER}/google-cloud-sdk/completion.bash.inc" ]; then
  . "/home/${USER}/google-cloud-sdk/completion.bash.inc"
fi

# Enables AWS command completion
#if [ -f "/home/${USER}/.local/bin/aws_completer" ]; then
#  complete -C "/home/${USER}/.local/bin/aws_completer" aws
#fi

# Enables Azure command completion
#if [ -f "/home/${USER}/azure-cli/az.completion" ]; then
#  source "/home/${USER}/azure-cli/az.completion"
#fi

# Enables minishift command completion
#if command -v minishift &>/dev/null; then
#  source <(minishift completion bash)
#fi

# Enables openstack command completion
#if command -v openstack &>/dev/null; then
#  source <(openstack complete --shell bash)
#fi
