# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
PATH="$HOME/.local/bin:$HOME/bin:$PATH"

# Go Environment
if [ -d $HOME/go/bin ]; then
    PATH="$HOME/go/bin:$PATH"
fi

if [ -f /home/${USER}/.gimme/envs/latest.env ]; then
    source "/home/${USER}/.gimme/envs/latest.env"
fi

export PATH
